# Welcome to Jekyll!
#

# Site settings
title: The Amplitude
description: |
  A Sound and Movement Performance

  Gabriele Reuter and Mattef Kuhlmey
banner: banner.jpg
owner: Gabriele Reuter # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: post@gabrielereuter.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/@reuterbraut
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:post@gabrielereuter.de
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UCe5_-e6D9X5r-zE1T1MDcAg
  #spotify:
  #stack-overflow:
  vimeo: https://vimeo.com/user23270149
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  soundcloud: https://soundcloud.com
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
